name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: wilfredo.castaneda.guerrero@gmail.com # ${{ secrets.DOCKER_USERNAME }} -> I should use Secrets from GITHUB, due to lack of permits I cannot
          password: 7ZP9PB44MgFkZag # ${{ secrets.DOCKER_PASSWORD }} -> I should use Secrets from GITHUB, due to lack of permits I cannot
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: willwarrior/article-indexer-scheduler:${{ github.sha }}
